heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: false
  reload.period: 5s

heartbeat.monitors:
- type: http
  id: backend-estimator
  name: Backend Estimator
  urls: ["http://localhost:8888/actuator/health"]
  schedule: '@every 5s'

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:

  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

processors:
  - add_observer_metadata:
      geo:
        name: us-east
        location: "37.926868, -78.024902"
